### ISSUE TITLE
Creating an infinitely recursive loop with map or macro causes stack overflow

### ISSUE THREAD

**Issue by MrPay** [vrapper/vrapper#509]
Simplest example, type <code>:map o o</code> then <code>o</code> to get <code>java.lang.StackOverflowError</code>

**Comment by keforbes** [comment]
@albertdev, now that #598 is fixed do you think we can close this defect too?

**Comment by albertdev** [comment]
@keforbes 
I'm afraid not, any attempt at a recursive macro or remap will still crash or at least offend your Eclipse instance.

I should have changed the naming of #598 because that was actually more of a feature request, it was implicitly asking for simple "append" remaps to work without triggering this nasty issue.

**Comment by McBrainy** [comment]
I just triggered the macro infinite recursion bug trying to write a macro to do something like #460 (convert an underscore_separated name to camelCase: `qqf_x~@qq`, haven't tried it in vim). I got a wheel of death, followed by Eclipse reporting a StackOverflowError, and then I finally force-quit Eclipse because my computer was getting hot. At this point, I think opening vim is the best way to do macros.

**Comment by albertdev** [comment]
@McBrainy 
This issue used to be about recursive remappings, but I've changed the title to include recursive macros as well.

There hasn't been any work so far to support recursive execution, and seeing how our motions don't signal an "end of boundary" error it would be hard to implement.

So far the idea was to just abort the execution, but that hasn't been started on either.

**Comment by albertdev** [comment]
I've got bad and good news:

* The bad news: Vrapper now detects that you're running an infinite recursive macro or mapping and will abort it &mdash effectively stopping you from using recursive macros do to cool stuff.

   Recursive macros and mappings still work, it's only when it encounters something which is already on the stack.
* The good news: you can no longer crash your Eclipse when doing this accidentally.

**Comment by albertdev** [comment]
If anybody watching this ticket still wants to see real "infinite" recursion implemented: please submit pull requests with fixes for our motion classes so that they raise some kind of event whenever they hit their "boundary". I don't have energy to go through them all and rebuild `MotionCommand` to catch such an event and call `EditorAdaptor.stopMacrosAndMappings()`, though at least some of the groundwork is now present.
