### ISSUE TITLE
Multiple Vrapper buttons in toolbar

### ISSUE THREAD

**Issue by oddRaven** [vrapper/vrapper#572]
When I installed the plugin everything was fine. Some start ups later a duplicate button appeared. Even later a third became visible.
![vrapper bug](https://cloud.githubusercontent.com/assets/9657411/5221094/367f5d14-7672-11e4-9f9d-78cefdcdae3c.png)
Version: Luna Service Release 1 (4.4.1)
Build id: 20140925-1800

**Comment by collinpeters** [comment]
I've had the same thing for awhile. I first noticed it when I toggled the Eclipse toolbar on and off. 
![eclipse](https://cloud.githubusercontent.com/assets/1203246/5895959/a39c36cc-a4e1-11e4-85e8-af909f25d908.png)

From the screenshots in #323, I also have many items in the 'Customize Perspective' area. In the past I have unchecked them so they are simply hidden, but more come over time. It seems the old ones have a label of 'toggle' now.
![eclipse2](https://cloud.githubusercontent.com/assets/1203246/5895991/1e6291da-a4e2-11e4-8e8f-36a2a87d907b.png)

**Comment by albertdev** [comment]
Is Vrapper the only one affected? Do you guys happen to experience a lot of crashes, or do you e.g. leave Eclipse running during shutdown which might cause it to be forcibly closed?

It seems that all those buttons are stored in `.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi` inside your workspace. Could you try to open this file when Eclipse is closed and look for Vrapper command ids?

It looks like there's an Eclipse bug for this problem: https://bugs.eclipse.org/bugs/show_bug.cgi?id=402561 - it's possible that we're not directly causing this.

**Comment by collinpeters** [comment]
Yes, Vrapper is the only icon affected. I don't get many Eclipse crashes, though of course Eclipse isn't the most stable either.

The workbench.xml has TONS of vrapper references. e.g. 
```
      <children xsi:type="menu:ToolBar" xmi:id="_JCJ9X6OHEeS8TPXD-LNR8g" elementId="net.sourceforge.vrapper.Vrapper" visible="false">
        <tags>Draggable</tags>
        <children xsi:type="menu:HandledToolItem" xmi:id="_JCJ9YKOHEeS8TPXD-LNR8g" elementId="net.sourceforge.vrapper.eclipse.commands.toggle" visible="false" iconURI="platform:/plugin/net.sourceforge.vrapper.eclipse/icons/icon.png" selected="true" type="Check" command="_JCLzdqOHEeS8TPXD-LNR8g">
          <persistedState key="IIdentifier" value="net.sourceforge.vrapper.eclipse/net.sourceforge.vrapper.eclipse.commands.toggle"/>
        </children>
```
The inner ```<children>``` item is repeated numerous times. The 'id' attribute is unique for each one.

https://www.dropbox.com/s/rlwaufso5bpvacp/workbench.xmi?dl=1

**Comment by darylsew** [comment]
I have the same issue; why would this be considered unconfirmed? On my windows 7 laptop this is an issue but on my windows 7 desktop it is not, so it's a curious bug.

**Comment by keforbes** [comment]
It's `unconfirmed` because we can't figure out how to reproduce the defect. It could be a defect in Eclipse, or it could be an issue with conflicting plugins.  We can't confirm that it's a defect in our code.  It may be, we just don't know.

**Comment by TheGuyWithTheFace** [comment]
I have experienced this as well, the workaround with removing excess items via the customize perspective menu worked for me for now, but I would also be interested in finding a long term fix for this.

**Comment by albertdev** [comment]
Is the problem still there if you switch to a new workspace? Note, don't select "Copy workspace layout", that would just infect the new one!

For those who switch workspaces more often, is the problem visible in multiple workspace or just a few of them?

**Comment by TheGuyWithTheFace** [comment]
After switching to a newly-created workspace I only see one icon. It remains to be seen if they start multiplying like they did in the other workspace, I will update if I see anything.

**Comment by dekpient** [comment]
I believe this is a bug in Eclipse (I might have seen the bug ticket as well, but I'm not entirely sure). The behaviour is gone now as off Mars.1 (4.5.1) build id: M20150904-0015. But I had to edit the `.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi` file manually though.

The trigger was hide and show the toolbar repeatedly and each time I got new icons for Ivy Resolve All and Vrapper.

**Comment by keforbes** [comment]
I'm closing this issue.  It was opened two years ago and sounds like it was fixed in Eclipse Mars.  There's nothing else being done for it unless we get new info.

**Comment by ch3sh1r** [comment]
Issue appeared again in Eclipse Neon same way as @oddRaven described:
![vrapper](https://cloud.githubusercontent.com/assets/441777/17925254/53d1e6c2-69fd-11e6-9aa4-6f97387d263a.png)
File `.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi` contains duplicate vrapper items:
```xml
...
      <children xsi:type="menu:ToolBar" xmi:id="_3JsFYmnbEeaEVsrdw5yASg" elementId="net.sourceforge.vrapper.Vrapper">
        <tags>Draggable</tags>
        <children xsi:type="menu:HandledToolItem" xmi:id="_3JsFY2nbEeaEVsrdw5yASg" elementId="net.sourceforge.vrapper.eclipse.commands.toggle" iconURI="platform:/plugin/net.sourceforge.vrapper.eclipse/icons/icon.png" selected="true" type="Check" command="_3JyOJWnbEeaEVsrdw5yASg">
          <persistedState key="IIdentifier" value="net.sourceforge.vrapper.eclipse/net.sourceforge.vrapper.eclipse.commands.toggle"/>
        </children>
        <children xsi:type="menu:ToolBarSeparator" xmi:id="_3JsFZGnbEeaEVsrdw5yASg" elementId="additions" toBeRendered="false">
          <tags>org.eclipse.jface.action.GroupMarker.GroupMarker(String)</tags>
        </children>
        <children xsi:type="menu:HandledToolItem" xmi:id="_3JsFZWnbEeaEVsrdw5yASg" elementId="net.sourceforge.vrapper.eclipse.commands.toggle" iconURI="platform:/plugin/net.sourceforge.vrapper.eclipse/icons/icon.png" selected="true" type="Check" command="_3JyOJWnbEeaEVsrdw5yASg">
          <persistedState key="IIdentifier" value="net.sourceforge.vrapper.eclipse/net.sourceforge.vrapper.eclipse.commands.toggle"/>
        </children>
      </children>
...
```
The removal of these lines helps but with each subsequent Eclipse launch new button appear.

Version: Neon Release (4.6.0)
Build id: 20160613-1800

**Comment by albertdev** [comment]
@ch3sh1r Sadly we still don't know what causes this.

As you can read above, some people didn't see it come back when they created a new workspace, but you might have to start from scratch rather than copying the layout or settings from a previous one.
